<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-28T18:08:23 IST" name="Suite" finished-at="2022-12-28T18:08:40 IST" duration-ms="16547">
    <groups>
    </groups>
    <test started-at="2022-12-28T18:08:23 IST" name="TestTwo" finished-at="2022-12-28T18:08:37 IST" duration-ms="13714">
      <class name="Tests.TwoTest">
        <test-method signature="TestTwo()[pri:0, instance:Tests.TwoTest@2c4d1ac]" started-at="2022-12-28T18:08:23 IST" name="TestTwo" finished-at="2022-12-28T18:08:37 IST" duration-ms="13675" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestTwo -->
      </class> <!-- Tests.TwoTest -->
    </test> <!-- TestTwo -->
    <test started-at="2022-12-28T18:08:23 IST" name="LoginTest" finished-at="2022-12-28T18:08:36 IST" duration-ms="12976">
      <class name="Tests.LoginTest">
        <test-method is-config="true" signature="open()[pri:0, instance:Tests.LoginTest@2f62ea70]" started-at="2022-12-28T18:08:23 IST" name="open" finished-at="2022-12-28T18:08:34 IST" duration-ms="11278" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open -->
        <test-method signature="login(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Tests.LoginTest@2f62ea70]" started-at="2022-12-28T18:08:34 IST" name="login" data-provider="getLoginData" finished-at="2022-12-28T18:08:36 IST" duration-ms="1439" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[amyraa702@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[MavenProject@1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Successfull]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.LoginTest@2f62ea70]" started-at="2022-12-28T18:08:36 IST" name="tearDown" finished-at="2022-12-28T18:08:36 IST" duration-ms="200" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.LoginTest -->
    </test> <!-- LoginTest -->
    <test started-at="2022-12-28T18:08:23 IST" name="TestThree" finished-at="2022-12-28T18:08:38 IST" duration-ms="14542">
      <class name="Tests.ThreeTest">
        <test-method signature="TestThree()[pri:0, instance:Tests.ThreeTest@29526c05]" started-at="2022-12-28T18:08:23 IST" name="TestThree" finished-at="2022-12-28T18:08:38 IST" duration-ms="14506" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestThree -->
      </class> <!-- Tests.ThreeTest -->
    </test> <!-- TestThree -->
    <test started-at="2022-12-28T18:08:23 IST" name="TestFour" finished-at="2022-12-28T18:08:40 IST" duration-ms="16547">
      <class name="Tests.FourTest">
        <test-method signature="TestFour()[pri:0, instance:Tests.FourTest@7a220c9a]" started-at="2022-12-28T18:08:23 IST" name="TestFour" finished-at="2022-12-28T18:08:36 IST" duration-ms="13326" status="FAIL">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at Tests.FourTest.TestFour(FourTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestFour -->
        <test-method is-config="true" signature="closure()[pri:0, instance:Tests.FourTest@7a220c9a]" started-at="2022-12-28T18:08:37 IST" name="closure" finished-at="2022-12-28T18:08:40 IST" duration-ms="2174" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closure -->
      </class> <!-- Tests.FourTest -->
    </test> <!-- TestFour -->
  </suite> <!-- Suite -->
</testng-results>
